server:
  error:
    include-stacktrace: on_param
  port: 8081

spring:
  application:
    name: Akashic
  datasource:
    url: jdbc:mysql://localhost:3306/book?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus